apiVersion: v1
kind: Service              # 1
metadata:
  name: coit-backend
  labels:
    app: coit-backend
spec:
  ports:
  - port: 80               # 3
    protocol: TCP          # 4
    targetPort: 80         # 5
  selector:                # 6
    app: coit-backend       # 7
